# 문제
- 1. 'subscribed'컬럼이 2024년 2월인 데이터 찾기 
- 2. 1중 f3컬럼이 gold인 데이터 개수 구하기

# 오답
- datetime으로 바꿔야함 -> pd.to_datetime

In [10]:
import pandas as pd
df = pd.read_csv("../data/type1_data1.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [12]:
#1. 
df['subscribed'] = pd.to_datetime(df['subscribed'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    datetime64[ns]
 9   views       116 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 9.5+ KB

In [13]:
fev = df[(df['subscribed'].dt.year == 2024 )& (df['subscribed'].dt.month == 2 )]
fev

        id   age city    f1  f2      f3    f4         f5 subscribed    views
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0
22    id22  -6.3   부산  72.0   1    gold  ENFP  52.667078 2024-02-09   6147.0
31    id31  86.0   부산  77.0   0    gold  ESFJ  73.586397 2024-02-11   8014.0
34    id34  65.0   부산   NaN   1  silver  INFP  48.431184 2024-02-01   3163.0
42    id42  65.0   대구  48.0   2    gold  ESTP  33.308999 2024-02-09   5999.0
55    id55  75.0   대구  63.0   2    gold  ENTP  13.049921 2024-02-06   6042.0
61    id61  87.0   경기  62.0   2     NaN  INTP  69.730313 2024-02-03    218.0
64    id64  43.0   경기  62.0   2    gold  ESFP  73.586397 2024-02-22   5995.0
86    id86   2.0   경기   NaN   0     NaN  ESTP  29.269869 2024-02-16   2155.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0

In [16]:
#2. 
gold = fev[fev['f3']=='gold']
gold

      id   age city    f1  f2    f3    f4         f5 subscribed   views
22  id22  -6.3   부산  72.0   1  gold  ENFP  52.667078 2024-02-09  6147.0
31  id31  86.0   부산  77.0   0  gold  ESFJ  73.586397 2024-02-11  8014.0
42  id42  65.0   대구  48.0   2  gold  ESTP  33.308999 2024-02-09  5999.0
55  id55  75.0   대구  63.0   2  gold  ENTP  13.049921 2024-02-06  6042.0
64  id64  43.0   경기  62.0   2  gold  ESFP  73.586397 2024-02-22  5995.0

In [17]:
answer = len(gold)
answer

5