## 문제

- 1. 주어진데이터에서 문자 자료형 컬럼 삭제
- 2. 숫자 자료형 컬럼의 결측치 0 대체
- 3. 각 행의 합이 3000 보다 큰 값의 개수를 정수로 구하기

## 오답
- select_dtypes (exclude!!!!!!)
- 각 행의 합 -> sum(axis=1)

In [1]:
import pandas as pd
df = pd.read_csv("../data/type1_data1.csv")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [9]:
#1.
col = df.select_dtypes(exclude = 'object').columns
drop_ob = df[col]

In [10]:
drop_ob

      age    f1  f2         f5   views
0     2.0   NaN   0  91.297791  6820.0
1     9.0  70.0   1  60.339826  2534.0
2    27.0  61.0   1  17.252986  7312.0
3    75.0   NaN   2  52.667078   493.0
4    24.0  85.0   2  29.269869  1338.0
..    ...   ...  ..        ...     ...
115  22.0  23.0   0   0.000000  9747.0
116  23.0  65.0   0   0.000000  5628.0
117  23.0  12.0   1   0.000000  1267.0
118  23.0  65.0   2   0.000000  6543.0
119  24.0  94.0   1   0.000000  2356.0

[120 rows x 5 columns]

In [11]:
#2.
drop_ob.fillna(0)

      age    f1  f2         f5   views
0     2.0   0.0   0  91.297791  6820.0
1     9.0  70.0   1  60.339826  2534.0
2    27.0  61.0   1  17.252986  7312.0
3    75.0   0.0   2  52.667078   493.0
4    24.0  85.0   2  29.269869  1338.0
..    ...   ...  ..        ...     ...
115  22.0  23.0   0   0.000000  9747.0
116  23.0  65.0   0   0.000000  5628.0
117  23.0  12.0   1   0.000000  1267.0
118  23.0  65.0   2   0.000000  6543.0
119  24.0  94.0   1   0.000000  2356.0

[120 rows x 5 columns]

In [16]:
#3.
count = drop_ob[drop_ob.sum(axis=1) > 3000]

In [18]:
len(count)

88